import os, os.path;

def list_prefix(in_list, what) :
	return [what + x for x in in_list];

def list_suffix(in_list, what) :
	return [x + what for x in in_list];

# directories
exe_name = 'bs_client';
tar_name = 'client';

# import custom settings
Import('*');

# construct base environ
base_env = custom_env.Clone();
base_env.Append(
	CPPDEFINES = ['BS_EXPORTING_PLUGIN'],
	CPPPATH = ['src', '#kernel/include', '#plugins/bs_cube/src']
);
boost_libs = list_suffix(list_prefix(['system', 'filesystem', 'regex', 'thread', 'signals', 'python'], 'boost_'), '-mt');
boost_libs_dbg = list_suffix(boost_libs, '-d');

# construct debug and release env
if build_kind == 'debug' :
	base_env.AppendUnique(
			LIBPATH = [os.path.join(tar_exe_dir, 'plugins')],
			LIBS = ['blue_sky_d', 'bs_cube_d']);
else :
	base_env.AppendUnique(
			LIBPATH = [os.path.join(tar_exe_dir, 'plugins')],
			LIBS = ['blue_sky', 'bs_cube']);

# build target
client = base_env.Program(target = os.path.join(tar_exe_dir, 'plugins', exe_name + '_d'), source = Glob(os.path.join('src', '*.cpp'), True, True));
# enable or disable dependencies
if base_env['nodeps'] == '1' :
	Ignore(client, bs_kernel);
	Ignore(client, bs_cube);
else :
	Depends(client, bs_kernel);
	Depends(client, bs_cube);
# make alias
base_env.Alias(tar_name, client);

# Install step
if base_env['install'] == '1':
	inst_tar = base_env.Install('$prefix', client);
	Alias(tar_name, inst_tar);

